// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/pizza.proto

package pizza

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PizzaNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PizzaNameRequest) Reset()         { *m = PizzaNameRequest{} }
func (m *PizzaNameRequest) String() string { return proto.CompactTextString(m) }
func (*PizzaNameRequest) ProtoMessage()    {}
func (*PizzaNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ab4986e65e8584, []int{0}
}

func (m *PizzaNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PizzaNameRequest.Unmarshal(m, b)
}
func (m *PizzaNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PizzaNameRequest.Marshal(b, m, deterministic)
}
func (m *PizzaNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PizzaNameRequest.Merge(m, src)
}
func (m *PizzaNameRequest) XXX_Size() int {
	return xxx_messageInfo_PizzaNameRequest.Size(m)
}
func (m *PizzaNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PizzaNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PizzaNameRequest proto.InternalMessageInfo

func (m *PizzaNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PizzaNameResponse struct {
	Pizza                *Pizza   `protobuf:"bytes,1,opt,name=pizza,proto3" json:"pizza,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PizzaNameResponse) Reset()         { *m = PizzaNameResponse{} }
func (m *PizzaNameResponse) String() string { return proto.CompactTextString(m) }
func (*PizzaNameResponse) ProtoMessage()    {}
func (*PizzaNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ab4986e65e8584, []int{1}
}

func (m *PizzaNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PizzaNameResponse.Unmarshal(m, b)
}
func (m *PizzaNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PizzaNameResponse.Marshal(b, m, deterministic)
}
func (m *PizzaNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PizzaNameResponse.Merge(m, src)
}
func (m *PizzaNameResponse) XXX_Size() int {
	return xxx_messageInfo_PizzaNameResponse.Size(m)
}
func (m *PizzaNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PizzaNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PizzaNameResponse proto.InternalMessageInfo

func (m *PizzaNameResponse) GetPizza() *Pizza {
	if m != nil {
		return m.Pizza
	}
	return nil
}

type PizzaIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PizzaIdRequest) Reset()         { *m = PizzaIdRequest{} }
func (m *PizzaIdRequest) String() string { return proto.CompactTextString(m) }
func (*PizzaIdRequest) ProtoMessage()    {}
func (*PizzaIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ab4986e65e8584, []int{2}
}

func (m *PizzaIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PizzaIdRequest.Unmarshal(m, b)
}
func (m *PizzaIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PizzaIdRequest.Marshal(b, m, deterministic)
}
func (m *PizzaIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PizzaIdRequest.Merge(m, src)
}
func (m *PizzaIdRequest) XXX_Size() int {
	return xxx_messageInfo_PizzaIdRequest.Size(m)
}
func (m *PizzaIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PizzaIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PizzaIdRequest proto.InternalMessageInfo

func (m *PizzaIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PizzaIdResponse struct {
	Pizza                *Pizza   `protobuf:"bytes,1,opt,name=pizza,proto3" json:"pizza,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PizzaIdResponse) Reset()         { *m = PizzaIdResponse{} }
func (m *PizzaIdResponse) String() string { return proto.CompactTextString(m) }
func (*PizzaIdResponse) ProtoMessage()    {}
func (*PizzaIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ab4986e65e8584, []int{3}
}

func (m *PizzaIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PizzaIdResponse.Unmarshal(m, b)
}
func (m *PizzaIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PizzaIdResponse.Marshal(b, m, deterministic)
}
func (m *PizzaIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PizzaIdResponse.Merge(m, src)
}
func (m *PizzaIdResponse) XXX_Size() int {
	return xxx_messageInfo_PizzaIdResponse.Size(m)
}
func (m *PizzaIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PizzaIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PizzaIdResponse proto.InternalMessageInfo

func (m *PizzaIdResponse) GetPizza() *Pizza {
	if m != nil {
		return m.Pizza
	}
	return nil
}

type Pizza struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pizza) Reset()         { *m = Pizza{} }
func (m *Pizza) String() string { return proto.CompactTextString(m) }
func (*Pizza) ProtoMessage()    {}
func (*Pizza) Descriptor() ([]byte, []int) {
	return fileDescriptor_21ab4986e65e8584, []int{4}
}

func (m *Pizza) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pizza.Unmarshal(m, b)
}
func (m *Pizza) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pizza.Marshal(b, m, deterministic)
}
func (m *Pizza) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pizza.Merge(m, src)
}
func (m *Pizza) XXX_Size() int {
	return xxx_messageInfo_Pizza.Size(m)
}
func (m *Pizza) XXX_DiscardUnknown() {
	xxx_messageInfo_Pizza.DiscardUnknown(m)
}

var xxx_messageInfo_Pizza proto.InternalMessageInfo

func (m *Pizza) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pizza) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*PizzaNameRequest)(nil), "pizza.PizzaNameRequest")
	proto.RegisterType((*PizzaNameResponse)(nil), "pizza.PizzaNameResponse")
	proto.RegisterType((*PizzaIdRequest)(nil), "pizza.PizzaIdRequest")
	proto.RegisterType((*PizzaIdResponse)(nil), "pizza.PizzaIdResponse")
	proto.RegisterType((*Pizza)(nil), "pizza.Pizza")
}

func init() { proto.RegisterFile("api/proto/pizza.proto", fileDescriptor_21ab4986e65e8584) }

var fileDescriptor_21ab4986e65e8584 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xc8, 0xac, 0xaa, 0x4a, 0xd4, 0x03, 0xb3, 0x85, 0x58,
	0xc1, 0x1c, 0x25, 0x35, 0x2e, 0x81, 0x00, 0x10, 0xc3, 0x2f, 0x31, 0x37, 0x35, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x56, 0x32, 0xe7, 0x12, 0x44, 0x52, 0x57, 0x5c, 0x90, 0x9f, 0x57, 0x9c,
	0x2a, 0xa4, 0xc4, 0x05, 0x31, 0x05, 0xac, 0x92, 0xdb, 0x88, 0x47, 0x0f, 0x62, 0x01, 0x58, 0x61,
	0x10, 0xd4, 0x02, 0x05, 0x2e, 0x3e, 0x30, 0xdf, 0x33, 0x05, 0x66, 0x3c, 0x1f, 0x17, 0x53, 0x66,
	0x0a, 0x58, 0x0b, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x29, 0x17, 0x3f, 0x5c, 0x05, 0x09, 0x06,
	0x6b, 0x73, 0xb1, 0x82, 0xf9, 0xd8, 0x9c, 0x0b, 0xb5, 0x83, 0x09, 0x66, 0x87, 0x51, 0x0f, 0x23,
	0x17, 0x0f, 0x58, 0x75, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x03, 0x17, 0x27, 0xdc,
	0x3f, 0x42, 0xe2, 0xc8, 0xe6, 0x23, 0x85, 0x84, 0x94, 0x04, 0xa6, 0x04, 0xc4, 0x85, 0x4a, 0x0c,
	0x42, 0x56, 0x5c, 0xec, 0x50, 0x67, 0x0b, 0x89, 0x22, 0x2b, 0x83, 0x7b, 0x54, 0x4a, 0x0c, 0x5d,
	0x18, 0xa6, 0xd7, 0x49, 0x30, 0x8a, 0x3f, 0x3b, 0xb1, 0x24, 0x31, 0x3e, 0xbd, 0xa8, 0x20, 0x19,
	0x12, 0x2b, 0x49, 0x6c, 0xe0, 0x68, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75, 0x9f, 0x54,
	0xbd, 0xaf, 0x01, 0x00, 0x00,
}
